active_storage を traceroute の除外対象に設定
直接アクセスしないと思うため
```
Unreachable action methods (8):
rake aborted!
Unused routes or unreachable action methods detected.
/home/runner/work/bootcamp/bootcamp/vendor/bundle/ruby/3.1.0/gems/traceroute-0.8.1/lib/tasks/traceroute.rake:23:in `block in <main>'
/home/runner/work/bootcamp/bootcamp/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/opt/hostedtoolcache/Ruby/3.1.0/x64/bin/bundle:25:in `load'
/opt/hostedtoolcache/Ruby/3.1.0/x64/bin/bundle:25:in `<main>'
Tasks: TOP => traceroute
(See full trace by running task with --trace)
  active_storage/base#send_stream
  active_storage/representations/base#send_stream
  active_storage/blobs/redirect#send_stream
  active_storage/blobs/proxy#send_stream
  active_storage/disk#send_stream
  active_storage/direct_uploads#send_stream
  active_storage/representations/redirect#send_stream
  active_storage/representations/proxy#send_stream
Error: Process completed with exit code 1.
```